# Generated by Django 4.1.5 on 2023-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
