# Generated by Django 4.1.5 on 2023-01-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlants', '0003_alter_userplant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='last_watering',
            field=models.DateField(null=True),
        ),
    ]
