# Generated by Django 4.1.5 on 2023-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlants', '0004_alter_userplant_last_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='last_watering',
            field=models.DateTimeField(null=True),
        ),
    ]
