# Generated by Django 4.1.5 on 2023-01-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('cientific_name', models.CharField(max_length=50)),
                ('water', models.IntegerField()),
                ('info', models.TextField(max_length=500)),
                ('image', models.CharField(max_length=200)),
                ('height', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_height', to='plants.limit')),
                ('lighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_lighting', to='plants.limit')),
                ('temperature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_temperature', to='plants.limit')),
            ],
        ),
    ]
