# Generated by Django 4.1.5 on 2023-01-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
